apiVersion: apps/v1
kind: Deployment
metadata:
  name: xlabs-venue-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xlabs-venue-api
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: xlabs-venue-api
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: xlabs-venue-api
        image: makeitrepeatable.azurecr.io/xlabs-venue-web:$(Build.BuildId)
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: xlabs-venue-api
spec:
  type: LoadBalancer
  ports:
  - port: 3000
  selector:
    app: xlabs-venue-api
